# Saved with iWrap 1.0.0
---
actor_description:
    actor_name: dina_imas
    actor_type: python
    data_type: legacy
code_description:
    documentation: DINA-Scenario actor for calculation of free-boundary equilibrium evolution 
    implementation:
        code_parameters:
            format: legacy-xml
            parameters: ./code_parameters.xml
            schema: ./code_parameters.xsd
        code_path: ./dina_imas.a
        data_dictionary_compliant: 3.39.0
        data_type: legacy
        include_path: ./dina_imas.mod
        programming_language: fortran
        root_dir: .
        subroutines:
            finalize:
                arguments:
                name:
                need_code_parameters: false
            get_state:
            get_timestamp:
            init:
                arguments:
                name:
                need_code_parameters: false
            main:
                arguments:
                -   intent: IN
                    name: em_coupling0
                    type: em_coupling
                -   intent: IN
                    name: equilibrium0
                    type: equilibrium
                -   intent: IN
                    name: magnetics0
                    type: magnetics
                -   intent: IN
                    name: pf_active0
                    type: pf_active
                -   intent: IN
                    name: pf_passive0
                    type: pf_passive
                -   intent: IN
                    name: wall0
                    type: wall
                -   intent: IN
                    name: core_profiles0
                    type: core_profiles
                -   intent: IN
                    name: core_sources0
                    type: core_sources
                -   intent: IN
                    name: bndcond_in
                    type: transport_solver_numerics
                -   intent: IN
                    name: pulse_schedule
                    type: pulse_schedule
                -   intent: OUT
                    name: equilibrium
                    type: equilibrium
                -   intent: OUT
                    name: magnetics
                    type: magnetics
                -   intent: OUT
                    name: pf_active
                    type: pf_active
                -   intent: OUT
                    name: pf_passive
                    type: pf_passive
                -   intent: OUT
                    name: core_profiles
                    type: core_profiles
                -   intent: OUT
                    name: core_sources
                    type: core_sources
                -   intent: OUT
                    name: core_transport
                    type: core_transport
                -   intent: OUT
                    name: summary
                    type: summary
                name: dina_step
                need_code_parameters: true
            set_state:
    settings:
        compiler_cmd: $FC
        compiler_flags: -Wl,--no-relax
        extra_libraries:
            path_defined:
            - ./dina_imas.a
            pkg_config_defined:
            - libxml-2.0
            - xmllib
        mpi_compiler_cmd:
...
