/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue Feb 27 21:53:45 2018
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 13
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
extern 	int scen_read(int i_en, int npf, int indx, int  *n, 
		double *t_val, double *tpl_val, double *pf_val );

extern int indx_calc(double *c0,double cb, int nc);

extern double interp(double *x, int idx, double u, double *y);
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

#define mexPrintf printf

/*
 * Output functions
 *
 */
void pf_lookup3_Outputs_wrapper(real_T *y0, 
                           const real_T  *n_pf, const int_T p_width0)
#define nmax 9997
#define kf 15
#define n_y0 500

{

	static int i_en=0;

	int i, res, nc, indx, k, j;
	int n[2];
	int num_pf, npf, n_max;
	double tt, y1, tt_val;
	
	static double pf_val[nmax];
	static double t_val[nmax],tpl_val[nmax];

	
	npf=11;

	i_en=i_en+1;

	num_pf=(int)*n_pf;

	y1=0;

	nc=200;

//		printf("---lookup2i_en, npf, num_pf  %d %d %d \n",i_en, npf, num_pf);

		res=scen_read(i_en, npf, num_pf, n, 
		t_val, tpl_val, pf_val );

//		n_max=(int)*n;
	    n_max=n[0];


		for (i = n_max+1; i < 1000; ++i) {
	
			t_val[i]=t_val[i-1]+1.;	        
		}

//		return

//		mexPrintf(" i_en num_pf n pf_val0 pf_valn %d %d %d %g  %g\n ",
			
//			i_en,num_pf,n_max,pf_val[0],pf_val[n_max]);

	    k=0;
//		for (i = 0; i <= n_max; ++i) {
		for (i = 0; i < n_y0; ++i) {
	
			y0[k] = t_val[i];	        
			k=k+1;
			y0[k] = tpl_val[i];
			k=k+1;
//			  mexPrintf(" i t tpl  %d %f %f  \n ",i,t_val[i],tpl_val[i]);
			for (j = 1; j <= npf; ++j) {
//			  mexPrintf(" pf %f \n ",pf_val[j+i*npf]);
			y0[k] =pf_val[j+i*npf];
			k=k+1;
			}
	//		  mexPrintf("  \n ");

		}
	
	nc=n[0];



	//y0[0]=1;
	
//	mexPrintf(" i_en num_pf t k %d %d %d \n ",i_en,num_pf,k);

}

int indx_calc(double *c0,double cb, int nc)

{
	int indx;
	int i;


	indx=0;
	for (i=1; i <= nc; i++){
		if (  c0[i] > cb  && indx == 0) indx = i;
	}
		indx=indx-1;

//	mexPrintf("tt t_1 t_nc nc indx= %g %g  %g  %d  %d\n",cb,c0[indx],c0[indx+1],nc,indx);

	return(indx);
}
	
double interp(double *x, int idx, double u, double *y)
{

  double ub;

  double num = y[idx+1] - y[idx];
  double den = x[idx+1] - x[idx];

  double m = num/den;
  
  ub=y[idx] + ( m * (u - x[idx]) );

return(ub);

}
