/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Oct 31 13:56:15 2018
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void pow_sup_Outputs_wrapper(const real_T *u0,
                          const real_T *u1,
                          real_T *y0 ,
			      const real_T  *xD,
                          const real_T  *n_mc, const int_T  p_width0, 
                          const real_T  *Tf, const int_T p_width1, SimStruct *S)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int j; static int N;
N=*n_mc;
/*mexPrintf(" N %d\n",N);mexPrintf(" Tfc= %g\n",Tfc);mexPrintf(" kl %d\n",kl);*/
/*if(kl==0){for(j=0;j<20;j++)X[j]=0; kl=1;};*/
/*mexPrintf(" X= %g %g %g\n",X[0],X{1],X{2]);*/
/*mexPrintf(" Tf= %g\n",Tf[2]);*/
for(j=0;j<N;j++){if(fabs(Tf[j])<1e-5) y0[j]=u1[j]; else y0[j]=xD[j];}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  * Updates function
  *
  */
void pow_sup_Update_wrapper(const real_T *u0,
                          const real_T *u1,
                          const real_T *y0 ,
                          real_T *xD, 
                          const real_T  *n_mc,  const int_T  p_width0,
                           const real_T *Tf, const int_T  p_width1, SimStruct *S)
{
  /* %%%-SFUNWIZ_wrapper_Update_Changes_BEGIN --- EDIT HERE TO _END */
int j; static int N; double A[20],B[20];

N=*n_mc; /*Tfc=*Tf;*/
for(j=0;j<N;j++){A[j]=exp(-u0[0]/Tf[j]); B[j]=1-A[j]; xD[j]=A[j]*xD[j]+B[j]*u1[j];}
/*for(j=0;j<N;j++)xD[j]=A[j]*xD[j]+B[j]*u1[j];*/
/* %%%-SFUNWIZ_wrapper_Update_Changes_END --- EDIT HERE TO _BEGIN */
}
