/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Nov 11 11:14:50 2018
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 50
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void read_gaps_Outputs_wrapper(real_T *y0, 
                           const real_T  *n_gaps, const int_T p_width0, SimStruct *S)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int N,i,j,k,N_g; static int kl0,kl1,kl2,kl3,kl4,kl5,kl6;
static double y_0[50][2],y1[50][2],y2[50][2],y3[50][2],y4[50][2],y5[50][2],y6[50][2];
FILE*f;char b[256];

N_g=*n_gaps; /*mexPrintf(" N_g %d\n",N_g);*/

if(N_g==0){
if(kl0==0){

f=fopen("elong_ref.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y_0[i],y_0[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y_0[j][k]=0;*/
for(j=i;j<50;j++){y_0[j][0]=y_0[j-1][0]+1; y_0[j][1]=y_0[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_0[j][k];
kl0=1;}return;}

if(N_g==1){
if(kl1==0){

f=fopen("g1.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y1[i],y1[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y1[j][k]=0;*/
for(j=i;j<50;j++){y1[j][0]=y1[j-1][0]+1; y1[j][1]=y1[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y1[j][k];
kl1=1;}return;}

if(N_g==2){
if(kl2==0){

f=fopen("g2.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y2[i],y2[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y2[j][k]=0;*/
for(j=i;j<50;j++){y2[j][0]=y2[j-1][0]+1; y2[j][1]=y2[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y2[j][k];
kl2=1;}return;}

if(N_g==3){
if(kl3==0){

f=fopen("g3.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y3[i],y3[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y3[j][k]=0;*/
for(j=i;j<50;j++){y3[j][0]=y3[j-1][0]+1; y3[j][1]=y3[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y3[j][k];
kl3=1;}return;}

if(N_g==4){
if(kl4==0){

f=fopen("g4.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y4[i],y4[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y4[j][k]=0;*/
for(j=i;j<50;j++){y4[j][0]=y4[j-1][0]+1; y4[j][1]=y4[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y4[j][k];
kl4=1;}return;}

if(N_g==5){
if(kl5==0){

f=fopen("g5.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y5[i],y5[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y5[j][k]=0;*/
for(j=i;j<50;j++){y5[j][0]=y5[j-1][0]+1; y5[j][1]=y5[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y5[j][k];
kl5=1;}return;}

if(N_g==6){
if(kl6==0){

f=fopen("g6.dat","r");fgets(b,255,f);
fscanf(f,"%d ",&N); fgets(b,255,f);
for(i=0;i<N;i++) fscanf(f,"%lf %lf",y6[i],y6[i]+1);
fclose(f);
/*for(k=0;k<N;k++)for(j=i;j<50;j++)y6[j][k]=0;*/
for(j=i;j<50;j++){y6[j][0]=y6[j-1][0]+1; y6[j][1]=y6[j-1][1];}
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y6[j][k];
kl6=1;}return;}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
