<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   elementFormDefault="qualified">
	   
   <xs:include schemaLocation="../imas_database.xsd" />  
  
  <xs:element name="parameters">
    <xs:complexType>
      <xs:all>
        <xs:element name="input_equilibrium" type="imas_database"/>
        <xs:element name="input_pf_active" type="imas_database"/>
        <xs:element name="input_pf_passive" type="imas_database"/>
        <xs:element name="input_magnetics" type="imas_database"/>
        <xs:element name="output" type="imas_database"/>       
        <xs:element name="grid" type="equilibrium_grid"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  
	<xs:complexType name="equilibrium_grid">
	  <xs:all>
		<xs:element name="nr" type="xs:integer"/>
		<xs:element name="nz" type="xs:integer"/>
		<xs:element name="rmin" type="xs:decimal"/>
		<xs:element name="rmax" type="xs:decimal"/>
		<xs:element name="zmin" type="xs:decimal"/>
		<xs:element name="zmax" type="xs:decimal"/>
	  </xs:all>
	</xs:complexType>
	
</xs:schema>
 
