/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Nov 11 11:13:57 2018
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
extern FILE*f1;
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 50

extern  struct t15_mem4 mem4;

struct t15_mem4
{
int N[7];
double y_1[50][2],y_2[50][2],y_3[50][2],y_4[50][2],y_5[50][2],y_6[50][2];
};

	 
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void read_gaps_term_Outputs_wrapper(real_T *y0, 
                           const real_T  *n_gaps, const int_T p_width0, SimStruct *S)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int N,i,j,k,N_g; static int k1,k2,k3,k4,k5,k6;
static double y_1[50][2],y_2[50][2],y_3[50][2],y_4[50][2],y_5[50][2],y_6[50][2];
FILE*f;char b[256];
int i2;


N_g=*n_gaps; /*mexPrintf(" N_g %d\n",N_g);*/

if(N_g==1){
if(k1==0){

	printf("---g1_term.dat \n");

N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_1[j][k]=mem4.y_1[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_1[j][k];

j=1;
printf("---g1_term.dat N y_01 y_02 %d %g %g \n",N,y_1[j-1][0],y_1[j-1][1]);
j=N-1;
printf("---g1_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_1[j-1][0],y_1[j-1][1]);
printf("---g1_term.dat j y_01 y_02 %d %g %g \n",j,y_1[j][0],y_1[j][1]);

printf("---g1_term-- end.dat \n");

//scanf("%d", &i2);


k1=1;}return;}

if(N_g==2){
if(k2==0){

	printf("---g2_term.dat \n");
N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_2[j][k]=mem4.y_2[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_2[j][k];

j=1;
printf("---g2_term.dat N y_01 y_02 %d %g %g \n",N,y_2[j-1][0],y_2[j-1][1]);
j=N-1;
printf("---g2_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_2[j-1][0],y_2[j-1][1]);
printf("---g2_term.dat j y_01 y_02 %d %g %g \n",j,y_2[j][0],y_2[j][1]);

printf("---g2_term-- end.dat \n");


k2=1;}return;}

if(N_g==3){
if(k3==0){

	printf("---g3_term.dat \n");
N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_3[j][k]=mem4.y_3[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_3[j][k];

j=1;
printf("---g3_term.dat N y_01 y_02 %d %g %g \n",N,y_3[j-1][0],y_3[j-1][1]);
j=N-1;
printf("---g3_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_3[j-1][0],y_3[j-1][1]);
printf("---g3_term.dat j y_01 y_02 %d %g %g \n",j,y_3[j][0],y_3[j][1]);

printf("---g3_term-- end.dat \n");
k3=1;}return;}

if(N_g==4){
if(k4==0){

	printf("---g4_term.dat \n");
N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_4[j][k]=mem4.y_4[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_4[j][k];

j=1;
printf("---g4_term.dat N y_01 y_02 %d %g %g \n",N,y_4[j-1][0],y_4[j-1][1]);
j=N-1;
printf("---g4_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_4[j-1][0],y_4[j-1][1]);
printf("---g4_term.dat j y_01 y_02 %d %g %g \n",j,y_4[j][0],y_4[j][1]);

printf("---g4_term-- end.dat \n");
k4=1;}return;}

if(N_g==5){
if(k5==0){

	printf("---g5_term.dat \n");

N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_5[j][k]=mem4.y_5[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_5[j][k];

j=1;
printf("---g5_term.dat N y_01 y_02 %d %g %g \n",N,y_5[j-1][0],y_5[j-1][1]);
j=N-1;
printf("---g5_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_5[j-1][0],y_5[j-1][1]);
printf("---g5_term.dat j y_01 y_02 %d %g %g \n",j,y_5[j][0],y_5[j][1]);

printf("---g5_term-- end.dat \n");
k5=1;}return;}

if(N_g==6){
if(k6==0){

	printf("---g6_term.dat \n");

N=mem4.N[N_g];

for(k=0;k<2;k++)for(j=0;j<50;j++)y_6[j][k]=mem4.y_6[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_6[j][k];

j=1;
printf("---g6_term.dat N y_01 y_02 %d %g %g \n",N,y_6[j-1][0],y_6[j-1][1]);
j=N-1;
printf("---g6_term.dat j-1 y_01 y_02 %d %g %g \n",j-1,y_6[j-1][0],y_6[j-1][1]);
printf("---g6_term.dat j y_01 y_02 %d %g %g \n",j,y_6[j][0],y_6[j][1]);

printf("---g6_term-- end.dat \n");
k6=1;}return;}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
