/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Nov 11 11:14:50 2018
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
extern FILE*f1;
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 50

extern struct t15_mem3 mem3;
struct t15_mem3
{
int N[7];
double y_0[50][2],y1[50][2],y2[50][2],y3[50][2],y4[50][2],y5[50][2],y6[50][2];
};

	  

	  /*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void read_gaps_Outputs_wrapper(real_T *y0, 
                           const real_T  *n_gaps, const int_T p_width0, SimStruct *S)
{

int N,i,j,k,N_g; static int kl0,kl1,kl2,kl3,kl4,kl5,kl6;

static double y_0[50][2],y1[50][2],y2[50][2],y3[50][2],y4[50][2],y5[50][2],y6[50][2];

int i2;


N_g=*n_gaps; /*mexPrintf(" N_g %d\n",N_g);*/

	printf("---READ_GAPS N_g== %d \n",N_g);


if(N_g==0){
if(kl0==0){

N=mem3.N[N_g];

printf("---elong_ref.dat N==  %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y_0[j][k]=mem3.y_0[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y_0[j][k];

j=1;
printf("---elong_ref.dat N y_01 y_02== %d %g %g \n",N,y_0[j-1][0],y_0[j-1][1]);
j=N-1;
printf("---elong_ref.dat j-1 y_01 y_02== %d %g %g \n",j-1,y_0[j-1][0],y_0[j-1][1]);
printf("---elong_ref.dat j y_01 y_02== %d %g %g \n",j,y_0[j][0],y_0[j][1]);

kl0=1;}
//printf("---READ_GAPS N_g kl0 y0  %d %d %g %g %g \n",N_g,kl0,y0[0],y0[1],y0[2]);
return;}

if(N_g==1){
if(kl1==0){

printf("---g1.dat \n");

N=mem3.N[N_g];

printf("---g1.dat N==   %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y1[j][k]=mem3.y1[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y1[j][k];

j=1;
printf("---g1.dat N y_01 y_02==  %d %g %g \n",N,y1[j-1][0],y1[j-1][1]);
j=N-1;
printf("---g1.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y1[j-1][0],y1[j-1][1]);
printf("---g1.dat j y_01 y_02==  %d %g %g \n",j,y1[j][0],y1[j][1]);

printf("---g1.dat end \n");

//stop:

kl1=1;}return;}

if(N_g==2){
if(kl2==0){

	printf("---g2.dat \n");


N=mem3.N[N_g];
printf("---g2.dat N==  %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y2[j][k]=mem3.y2[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y2[j][k];

j=1;
printf("---g2.dat N y_01 y_02==  %d %g %g \n",N,y2[j-1][0],y2[j-1][1]);
j=N-1;
printf("---g2.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y2[j-1][0],y2[j-1][1]);
printf("---g2.dat j y_01 y_02==  %d %g %g \n",j,y2[j][0],y2[j][1]);

printf("---g2.dat end \n");

kl2=1;}return;}

if(N_g==3){
if(kl3==0){

	printf("---g3.dat \n");

N=mem3.N[N_g];

printf("---g3.dat N==   %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y3[j][k]=mem3.y3[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y3[j][k];

j=1;
printf("---g3.dat N y_01 y_02==  %d %g %g \n",N,y3[j-1][0],y3[j-1][1]);
j=N-1;
printf("---g3.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y3[j-1][0],y3[j-1][1]);

kl3=1;}
//printf("---READ_GAPS N_g kl3 y0  %d %d %g %g %g \n",N_g,kl3,y0[0],y0[1],y0[2]);
return;}

if(N_g==4){
if(kl4==0){

	printf("---g4.dat \n");

N=mem3.N[N_g];

printf("---g4.dat N==   %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y4[j][k]=mem3.y4[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y4[j][k];

j=1;
printf("---g4.dat N y_01 y_02==  %d %g %g \n",N,y4[j-1][0],y4[j-1][1]);
j=N-1;
printf("---g4.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y4[j-1][0],y4[j-1][1]);
printf("---g4.dat j y_01 y_02== %d %g %g \n",j,y4[j][0],y4[j][1]);

printf("---g4.dat end \n");

kl4=1;}return;}

if(N_g==5){
if(kl5==0){

	printf("---g5.dat \n");

N=mem3.N[N_g];

printf("---g5.dat N==   %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y5[j][k]=mem3.y5[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y5[j][k];

j=1;
printf("---g5.dat N y_01 y_02== %d %g %g \n",N,y5[j-1][0],y5[j-1][1]);
j=N-1;
printf("---g5.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y5[j-1][0],y5[j-1][1]);
printf("---g5.dat j y_01 y_02==  %d %g %g \n",j,y5[j][0],y5[j][1]);

printf("---g5.dat end \n");
kl5=1;}return;}

if(N_g==6){
if(kl6==0){
	printf("---g6.dat \n");
N=mem3.N[N_g];

printf("---g6.dat N==   %d  \n",N);

for(k=0;k<2;k++)for(j=0;j<50;j++)y6[j][k]=mem3.y6[j][k];
for(k=0;k<2;k++)for(j=0;j<50;j++)y0[k+j*2]=y6[j][k];

j=1;
printf("---g6.dat N y_01 y_02==  %d %g %g \n",N,y6[j-1][0],y6[j-1][1]);
j=N-1;
printf("---g6.dat j-1 y_01 y_02==  %d %g %g \n",j-1,y6[j-1][0],y6[j-1][1]);
printf("---g6.dat j y_01 y_02== %d %g %g \n",j,y6[j][0],y6[j][1]);

printf("---g6.dat end \n");
kl6=1;}return;}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
