/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Nov 11 11:14:33 2018
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
extern FILE*f;
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 500

struct t15_mem2
{
int N; double y[500][20];
int k_time; 
};

extern struct t15_mem2 mem2;
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void read_volt_Outputs_wrapper(real_T *y0, 
                           const real_T  *n_mc, const int_T p_width0, SimStruct *S)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int i,j,k,N; static int kl; static double y[500][20];char b[256];
int k_time, ii; double y2; 

if(kl==0){
	printf("+++volt.dat \n");
	N=mem2.N; /*mexPrintf(" N %d\n",N);*/
	k_time=mem2.k_time;

for(k=0;k<k_time;k++){
	printf("+++k==   %d\n",k);
for(ii=0;ii<N;ii++){
	y[k][ii]=mem2.y[k][ii];}
}


k=1;
printf("+++k==   %d\n",k);
for(ii=0;ii<N;ii++){
printf(" %g",y[k][ii]);
}
printf("\n");
k=10;
printf("+++k==   %d\n",k);
for(ii=0;ii<N;ii++){
printf(" %g",y[k][ii]);
}
printf("\n");
k=k_time-1;
printf("+++k==   %d\n",k);
for(ii=0;ii<N;ii++){
printf(" %g",y[k][ii]);
}
printf("\n");

i=k_time;

printf("+++i  N  ii k %d %d %d %d\n",i,N,ii,k);

//fclose(f);
/*mexPrintf(" i %d\n",i);*/
for(k=0;k<N;k++)for(j=i;j<500;j++)y[j][k]=0;
for(j=i;j<500;j++)y[j][0]=y[j-1][0]+1;
kl=1;}

for(k=0;k<20;k++)for(j=0;j<500;j++)y0[k+j*20]=y[j][k];
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
